---
- name: prep docker server
  hosts: tag_docker
  gather_facts: true
  become: true
  roles:
    - role: docker_common_setup

- name: configure docker infra node
  hosts: node121
  become: true
  roles:
    - docker_infra_node
    - docker_common_services

- name: configure docker service node
  hosts: node122
  become: true
  roles:
    - docker_service_node
    - docker_common_services
